create schema if not exists "junowot";

create or replace view "junowot"."user" as
select id, email, raw_user_meta_data ->> 'username' as username
  from auth.users u
;

create table "junowot"."league" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "owner" uuid not null default auth.uid(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "junowot"."league" enable row level security;

create table "junowot"."league_member_status" (
    "code" character varying not null default '''pending'''::character varying
);


alter table "junowot"."league_member_status" enable row level security;

create table "junowot"."league_member" (
    "id" bigint generated by default as identity not null,
    "league_id" bigint not null,
    "member_uuid" uuid not null,
    "status_code" character varying not null default 'pending'::character varying,
    "is_curator" boolean not null default false,
    "updated_at" timestamp with time zone not null default now()
);

alter table "junowot"."league_member" enable row level security;

CREATE UNIQUE INDEX league_member_pkey ON junowot.league_member USING btree (id);

CREATE UNIQUE INDEX league_member_ux2 ON junowot.league_member USING btree (member_uuid, league_id);

CREATE UNIQUE INDEX league_member_status_code_key ON junowot.league_member_status USING btree (code);

CREATE UNIQUE INDEX league_pkey ON junowot.league USING btree (id);

CREATE UNIQUE INDEX league_ux2 ON junowot.league USING btree (owner, name);

alter table "junowot"."league" add constraint "league_pkey" PRIMARY KEY using index "league_pkey";

alter table "junowot"."league_member" add constraint "league_member_pkey" PRIMARY KEY using index "league_member_pkey";

alter table "junowot"."league_member" add constraint "league_member_league_id_fkey" FOREIGN KEY (league_id) REFERENCES junowot.league(id) not valid;

alter table "junowot"."league_member" validate constraint "league_member_league_id_fkey";

alter table "junowot"."league_member" add constraint "league_member_status_code_fkey" FOREIGN KEY (status_code) REFERENCES junowot.league_member_status(code) not valid;

alter table "junowot"."league_member" validate constraint "league_member_status_code_fkey";

alter table "junowot"."league_member_status" add constraint "league_member_status_code_key" UNIQUE using index "league_member_status_code_key";